### ISSUE TITLE
Questions, GCM/Data/PushEvent

### ISSUE THREAD

**Issue by localnerve** [gauntface/simple-push-demo#11]
First, thanks for this great demo!

I'm really liking this, but disappointed I can't even send a topic-string or any id through to Chrome with the PushEvent to resolve a specific data payload. I guess there is always event.timeStamp :-(.

I see that Firefox supports the PushEvent.data property, but have found [other evidence via MDN](https://github.com/marco-c/web-push/blob/d7764eaa06eac2c6e3a633b15f22d5112d5f5cc7/index.js#L66) that suggests that GCM will not even support a data payload for web-push, which contradicts the [GCM doc](https://developers.google.com/cloud-messaging/http-server-ref).

Questions
1. Is the data limitation totally in Chrome, or also partly in GCM?
2. Is there an issue/thread I can monitor for Chrome development progress besides [this one](https://code.google.com/p/chromium/issues/detail?id=486040)?
3. Are there any alternatives to GCM for the 'web push' space?

Thanks again for this demo, and thanks for taking the time to read my questions.

**Comment by gauntface** [comment]
The payload is a limitation on all browsers until fairly recently when the spec has been getting finalised.

That is exactly the thread you want to be following. Pete is doing a lot of the work in this.

The subscription endpoint is provided by the browser. If you look at Firefox nightly they have a different push service provider.

The reason data hasn't existed is because encryption was required. In the very early days of push implementation in Chrome, payload was actually supported. We are hoping to have a demo with encryption soon.

**Comment by ravikrn** [comment]
If data or id is not supported by pushEvent, then how can we generate data in service-worker. Even if we have API in service-worker, that API would need some parameter. Without parameter, it wont be efficient API. If I send two notifications at same time for two different users, I wont be able to get different message just by using event.timestamp
