### ISSUE TITLE
doesn't work on my phone (Samsung a5 on android 7 with chrome 61.0.3163.98)

### ISSUE THREAD

**Issue by henrylearn2rock** [gauntface/simple-push-demo#180]
it asks for permission, allowed, but nothing happen after clicking "send a push via xhr.

**Comment by gauntface** [comment]
Sadly I'm not sure I can help with the current information as I don't have a Samsung A5 and the demo works on my phone for Chrome v62 (which is the latest Chrome stable).

Could you try on Chrome Beta and see if it works. Otherwise, if you connect the device to your computer via USB and open `chrome://inspect`and click "inspect" for the simple push demo, do you see any error messages?

**Comment by henrylearn2rock** [comment]
Thanks!  Chrome beta works. 

I just checked app store and I see no update available for my 61.0.3163.98 yet. Weird.

Thanks again!
