### ISSUE TITLE
.git folder is MASSIVE

### ISSUE THREAD

**Issue by MasterScrat** [gauntface/simple-push-demo#193]
I was curious why this small project took so long to clone:

```
/simple-push-demo/.git [master]$ du -sh
130M	.
```

**Comment by gauntface** [comment]
It's possible / very likely that node_modules were accidentally committed. I'm not sure how to remove them from the history though.

I tried using `git filter-repo --invert-paths --path node_modules` but that doesn't seem to have made a meaningful impact.

If anyone sees this and is able to help, please re-open this issue:

1. Help debug further (i.e. confirm node_modules is the issue vs something else)
1. Knows how to reduce size of the repo without wiping out contributors.

Due to the age of this issue (sorry for not responding sooner) I'm going to close this.
