### ISSUE TITLE
Library / minimal example / documentation

### ISSUE THREAD

**Issue by pwFoo** [gauntface/simple-push-demo#195]
Hi, I found your demo page and it works very well, but it isn't a documented library to use.
Could you provide a minimal example how to use? Some more documentation?

**Comment by pwFoo** [comment]
Hi @gauntface I like how your example works, but would be nice to have some more documentation about (minimal) setup. Without GA, design, ...

**Comment by gauntface** [comment]
@pwFoo have you seen https://web-push-book.gauntface.com/ ? There is a demo here: https://github.com/gauntface/web-push-book/tree/master/src/demos

**Comment by pwFoo** [comment]
Thanks @gauntface I have to take a look into it and the examples / demo.

Could you recommend a client and (php) server library / framework to use or should I try to put the web-push-book examples / demos together?

Needed features should be 

- encryption (needed to push custom data?)
- support browsers push services
- closed browser / app support (service worker)

If there is a working and (ideally) supported lib / framework with the needed features I would use it instead of build it myself.

**Comment by gauntface** [comment]
I would recommend reading the book and you should be able to find libraries here: https://github.com/web-push-libs

**Comment by jimmywarting** [comment]
I too would also like to se a Library / minimal example
I know about nodes web-push lib but i like yours a bit more since it's more at vanilla JS. And don't require so many other dependencies. Also it uses nothing but standard web technologies (web crypto for instance) so everything can technically work in the browser without bundling up lots of node specific stuff.

Would be cool if you could separate out the webpush from the UI

And instead of curl that isn't compatible of displaying a byte stream when you have a payload, could you instead show some example that uses the fetch api instead?
I know for a fact that mozilla's endpoint allows CORS request so it is technically possible to send webpush with nothing but client side request - i hope chrome adds that too... (https://github.com/w3c/push-api/issues/303)
