### ISSUE TITLE
Simple push notification fails on Samsung Galaxy S10

### ISSUE THREAD

**Issue by RiedigerD2** [gauntface/simple-push-demo#199]
Honestly I don't know who to log this issue with. It might be a bug with the latest Android OS on the S10. I am using browserstack which is apparently testing on real devices. 
Using this site https://gauntface.github.io/simple-push-demo/
Gives the error 
Ooops a Problem Occurred
abortError: Regsitration failed - push service error

The device is Android Version 9
One UI version 1.1(I don't even know what this is)

**Comment by gauntface** [comment]
Sorry for not getting back to this sooner.

It's very likely that this was an issue with site OR with the way the device was configured.

I'm going to close this since the latest changes will have addressed the issue for the site and if it's still occurring on the device, I suspect it's an issue with browserstack (perhaps not being able to grant notification permissions or not being configured with a push provider).
