### ISSUE TITLE
support push response in website

### ISSUE THREAD

**Issue by FugDev** [gauntface/simple-push-demo#9]
print event.data pushed on website instead of status bar in android

**Comment by gedw99** [comment]
I got to admit. I was a little annoyed that the push must go through Google service. It binds my application development to Google.

I wonder how apple, M's and Mozilla are going to provide this.

Then you have to allow for what happens on desktop.

In the end I will have to sniff what device the user is on, and then choose which service / company I need to make the push through ??

**Comment by gauntface** [comment]
There are two things to discuss here.

1.) The idea with the push protocol is that you as the web app developer shouldn't have to care who the push provider is. I just updated this demo to work with Firefox Nightly (although showNotification is working for me - but check the console and you'll see a push message received event). With that update you'll notice I never have to examine the endpoint at all. (This if statement is skipped and a request is made straight to the end point: https://github.com/gauntface/simple-push-demo-backend/blob/master/main.py#L37).

2.) The reason this isn't true for Chrome today is that GCM needs to implement the 'Web Push Protocol' to make it so that you don't have to do any extra checking of what the endpoint is: http://datatracker.ietf.org/doc/draft-thomson-webpush-protocol/

@FugDev Regarding printing data on the web page - when you receive a push you *HAVE* to show a notification if the browser is closed / the user isn't viewing one of your pages. If they are viewing one of your pages you don't have to show a notification and send a message to web page to update the UI anyway you want.

To check if the user has one of your pages open check: https://github.com/GoogleChrome/samples/blob/gh-pages/push-messaging-and-notifications/service-worker.js#L28

To send a message to the page, this demo should help you out: https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker/post-message
